In [1]:
import requests as req

### 네이버 페이지 요청하기

In [2]:
res = req.get("http://www.naver.com")

### 응답 확인

In [3]:
res

In [4]:
res.text

'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta property="og:title" content="네이버"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta name="twitter:card" content="summary"> <meta name="twitter:title" content=""> <meta name="twitter:url" content="https://www.naver.com/"> <meta name="twitter:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta name="twitter:description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta name="google-site-verification" content="uru5NJKa1Bfr5nv5AdQ26Qat7UrPU_02l-PIZRLzI-g"/> <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?1"> <link rel="apple-touch-icon-precomposed" href="https://s.pstatic.net/static/www/nFavicon96.png"/> <link rel="apple-touch-icon" sizes="114x114" href="https://s.pstatic.net/static/www/u/2014/0328/mma_204243574.png"/> <link rel="apple-touch-icon" href="https://s.pstatic.net/static/www/u/2014/0328/mma_20432863.png"/> <link rel="stylesheet" href="https://ssl.pstatic.net/sstatic/search/pc/css/sp_autocomplete_251001.css"> <link rel="canonical" href="https://www.naver.com/"> <link rel="alternate" media="only screen and (max-width: 767px)" href="https://m.naver.com/"> <script>window.gladsdk=window.gladsdk||{},window.gladsdk.cmd=window.gladsdk.cmd||[],window.ndpsdk=window.ndpsdk||{},window.ndpsdk.cmd=window.ndpsdk.cmd||[],window.ndpsdk.polyfill=window.ndpsdk.polyfill||{cmd:[]};var g_ssc="navertop.v5";window.nsc=g_ssc,window.nmain=window.nmain||{},window.nmain.jsOrigin="www"</script> <script>window.ntm=window.ntm||[]</script> <script async src="https://ssl.pstatic.net/tveta/libs/ndpsdk/prod/ndp-loader.js"></script> <script async src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js"></script> <script src="https://ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js" defer="defer"></script>  <script>\nwindow["EAGER-DATA"] = window["EAGER-DATA"] || {};\nwindow["EAGER-DATA"]["PC-FEED-WRAPPER"] = {"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"PC-FEED-BLOCK","excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-TOP","@template":"HIGHLIGHTED-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"제대로 가슴 열고 계세요?","url":"https://tv.naver.com/h/92052918","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260112_264%2FIR8iu_17681848662080h1Sn_JPEG%2Fug52PqoQ6O_01.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/momentfit","name":"모멘트핏 록코치","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20250620_278%2FFHzU9_1750411479403pSfht_JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:41"},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a642"},{"@type":"MATERIAL-PC-FEED","title":"빙판길 낙상 후 지속되는 허리 통증, 단순 타박상 아닌 ‘요추 염좌’ 의심해야","url":"https://blog.naver.com/hidoc2010/224140113727","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMDlfMTAg%2FMDAxNzY3OTE4MTgzODkx.8stqLJfxAdZmm92-KhXcpTlxnCxXJ5UV5oKrY7F9YRIg.xlUrB9TS5uPXgu5yUOiRjSyAB_XBuiOTQODIi5j8FYQg.JPEG%2F%EC%B9%BC%EB%9F%BC_%EC%98%A4%ED%98%84%EC%8A%B9.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/hidoc2010","name":"HiDoc","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTAxMTNfMjc1%2FMDAxNzM2Njk0MzYyMzAw.GuaoZjexNlnF_2Vlv_k8_9IAlK0vm3zhInyW59Ayui4g.clkoN60GH1o5ELJXuaJoQm73nwIOUAsPvYNB7EB66ngg.PNG%2FHiDoc_BI_200_200.png%2FHiDoc_BI_200_200.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a643"},{"@type":"MATERIAL-PC-FEED","title":"cj자메이카 치킨 리뷰","url":"https://tv.naver.com/h/92052464","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260112_158%2FVy2Mi_1768184439060rcOsF_JPEG%2FAFn8C33njr_08.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/jamview","name":"JAMBRO","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20250103_275%2FTvJjX_1735890025897vfRg7_PNG%2F1735890025831.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:27"},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a644"},{"@type":"MATERIAL-PC-FEED","title":"먹는 거 좋아하는데 7kg 감량! 20대 같은 30대 박서준 님의 관리 비결은?!","url":"https://blog.naver.com/again_2s/224143296895","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTJfMTEg%2FMDAxNzY4MTc4NjkxOTA3.aABxzbiI3JYgXL6SOr9lNhAdazn1hM3jaOXZP0-dNgsg.puFW9LQTHw4qKo94uMdB3_jCKgwLVFGPMgfSefUDHMkg.PNG%2Fimage.png%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/again_2s","name":"또또들","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTA5MTVfMjIx%2FMDAxNzU3OTM3NzQ3Mjgy.4yqz0AIgYfPlbUn7yTdb9M5HaDIS3QnIzOV3WSXy3FEg.mTp5khf2WszXpGh68_gc2SBehlG3NejsUtkFixL-occg.PNG%2FKakaoTalk_20250501_144550047.png%2FKakaoTalk_20250501_144550047.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a645"},{"@type":"MATERIAL-PC-FEED","title":"현미, 잡곡밥 먹으면 내 몸에 일어나는 변화","url":"https://tv.naver.com/h/92052421","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260112_148%2Fl4Sqx_1768184370461GzCcf_JPEG%2FOdU9zeVWdl_03.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/knowledgeflavor","name":"지식의 맛","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20241220_28%2F0EXkR_1734671515787jnYJz_JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:29"},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a646"},{"@type":"MATERIAL-PC-FEED","title":"고단백 식단 성공하는 사람들, “이 조합”입니다","url":"https://blog.naver.com/sung9875/224142414340","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTFfMjg0%2FMDAxNzY4MTAzNDQ5NTcy.mov5CHraeRz22HWjCDXujADKh8nr5pXW8yHCkjawuFsg.53eJgjft9GbjCN-ZOhdOPDKMtw3o-fkK3MpPlZZXL9Ug.PNG%2Fimage.png%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/sung9875","name":"SmileDay","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMTExMTBfMjU5%2FMDAxNjM2NTAwMTAyNTM3.C7HM1KgelyXYXrq7Sf6oTgHi3BdfZFBExpK8lKNRkPMg.fFDqoKfSho6g8tn5cijZsfdqgo-qr2t0r-nuBVdE6RYg.PNG.sung9875%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a647"},{"@type":"MATERIAL-PC-FEED","title":"밴드 하나로 상체+코어+하체","url":"https://tv.naver.com/h/92051812","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260112_72%2FWDztP_1768183827475QaKih_JPEG%2FOIuZGjfc95_01.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/adelinepialtes","name":"아델린필라테스","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20221208_94%2FXDkTA_1670470159011z1XnV_JPEG%2F1670470158950.JPG%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:14"},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a648"},{"@type":"MATERIAL-PC-FEED","title":"2026년에는 무조건 성공하는 1년치 식단표","url":"https://blog.naver.com/supia2728/224140879483","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMDhfMjQ3%2FMDAxNzY3ODM4NTkxNjUw.e99zmukhx4VOE61EHYwHfNXC0Qlmc7Fsr6zM7hy8gjAg.2bLfyBhe43R0lrkw2Vc3MIVcyVYVSk9XZTo1EYElW5Eg.JPEG%2Foutput%EF%BC%BF3096781838.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/supia2728","name":"지니츄","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMjExMTNfOTYg%2FMDAxNjY4MjkzNzY3Njgx.OQzhh0AnLRkjro1VKIHYW59ieYCVvcuj-ZERbN5N_fYg.ByZj2jmt2fJGcoU3x1Asl4Zc7uZ-beBL3z5wsh9rflsg.PNG.supia2728%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a649"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-AIRS-PAGE-1","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"이 음식은 꼭 아침에만 먹어요","url":"https://blog.naver.com/kies84/224142668365","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTFfMTY2%2FMDAxNzY4MTIyMzAxMTc5.WK8_DdCvxR_EBcwqC_VT-yf0TdQNZeKHRPE9eS4BY-Ug.zftjCki6Ynw4ceYVVXoNeXgYvrD2VXlCzgHx73hMPaEg.JPEG%2F%EC%95%84%EC%B9%A8-%ED%98%88%EB%8B%B9-%EC%98%A4%ED%8A%B8%EB%B0%80-.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/kies84","name":"초대리","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2F20151118_91%2Fkies84_1447826769906Cp9pH_JPEG%2Fttt.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cbe"},{"@type":"MATERIAL-PC-FEED","title":"혈당스파이크 걱정 끝! 뱃살 빠지는 다이어트 꼬마김밥 만들기","url":"https://tv.naver.com/v/92024748","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260111_172%2FGFqvj_1768141100225eDcv4_JPEG%2Fimage.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/ramble","name":"램블부부TV","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20150501_12%2FVgljR_1430463434874hf2JN_JPEG%2F1430463434861.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:51"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cbf"},{"@type":"MATERIAL-PC-FEED","title":"급격한 체중 증가 신호, 식단보다 먼저 무너진 식사 패턴","url":"https://blog.naver.com/chojy0307/224142441465","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTFfMjYy%2FMDAxNzY4MTA1MjAzOTQy.lyF6_NXzafYL-t201yd_63_DcQ04w3bNi1mEFl4n0tQg.mNy_tdb1PqmcIKnw_td-cYzNuwh7E4Xdt-t3v6yfqFUg.JPEG%2F900%EF%BC%BF1764906151033.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/chojy0307","name":"힐데리다","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDEyMjVfMjk5%2FMDAxNzM1MTI4NjU1Njcw.-VdMnuvSRkONyE-6ehR7ZoodFFshcq5HA1JJ6MnR1mIg.Xc_GJUxXq_5qnyJE5eD_C7J-2amPzb1eyuQ1M6kgI1Ug.JPEG%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc0"},{"@type":"MATERIAL-PC-FEED","title":"여자 아랫배 복근 운동 레그레이즈 하복근운동 팁","url":"https://blog.naver.com/artmxn/224142495283","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTFfMjQx%2FMDAxNzY4MTA5ODI2MzQ5.preSeQB2Jl83OV1j4yvzh9NumUuBARhtGcyymjdk3BYg.8hP6IOdDY6JqMPnAPqP1zxv2-eL0A8onEXKVYqWtGyUg.JPEG%2F%EB%B3%B5%EA%B7%BC_9.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/artmxn","name":"세리나","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMzExMDlfMTcz%2FMDAxNjk5NTIzMTc2Mjk5.XG9lgf3FllTNOqhokuqgxZJwZJAyFTbYGc8DT8045XQg.ka4dlszNL13QPuW5Cno6MmBxWMNK8ETF54xXHUPUoikg.PNG.artmxn%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc1"},{"@type":"MATERIAL-PC-FEED","title":"밴드 하나로 상체+코어+하체","url":"https://tv.naver.com/v/92051636","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260112_67%2FeOFKF_1768183679526JkNhf_JPEG%2FLqPsiuvJah_02.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/adelinepialtes","name":"아델린필라테스","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20221208_94%2FXDkTA_1670470159011z1XnV_JPEG%2F1670470158950.JPG%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:14"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc2"},{"@type":"MATERIAL-PC-FEED","title":"딸기 고를때 이것만 기억하세요!","url":"https://tv.naver.com/h/91951532","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260110_118%2FuTK4K_1768015815971PcPAE_JPEG%2F8F788DB7-E2DA-443A-8FFF-6ADA92A079E6.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/misulin","name":"미슐린","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20241021_288%2FMfZdF_1729517520156KbP6K_JPEG%2F1729517520134.jpeg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:23"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc3"},{"@type":"MATERIAL-PC-FEED","title":"방학식단, 고등학생 집밥, 라이딩도시락 오늘뭐먹지","url":"https://blog.naver.com/mykim0403/224141982272","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTBfMTU1%2FMDAxNzY4MDUyMDU0Nzcy.IJclwtphE2yg8lqnmg3NLChviBsUQhd7tPIdyqtnW0Mg.Qjb5hFD-JG_FKXPfyyyxM4Pfd_9M2RMrGSFHqSGOWRQg.JPEG%2F1768052053500.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/mykim0403","name":"은효맘미미","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMTEyMjNfNzYg%2FMDAxNjQwMTg2MDI5NTg5.Tnn8ON9qLPRvX-mSM9v25ggHUH9UPj7gstH6cWqsYJIg.cKno2aj8KWpLqf-X3eMtnDuSuguHsp5NU_FPRJhea-Ig.JPEG.mykim0403%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc4"},{"@type":"MATERIAL-PC-FEED","title":"배에 가스 차고 잦은 방귀 이것만 알면 진짜로 없어집니다. 장 속 염증 제거 하는 꿀팁!","url":"https://tv.naver.com/v/91887267","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260109_163%2FDBK9E_1767929545613u2YPI_JPEG%2Fimage.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/geonnamultv","name":"건나물TV","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240202_57%2F6q1mF_1706857092078wB5SF_PNG%2F1706857092056.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"09:11"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc5"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-AIRS-PAGE-2","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"\\"사람 맞아...?\\" 카리나가 연습생 때부터 했던 이 운동은?","url":"https://blog.naver.com/pshhh9301/224141691616","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTBfMjI1%2FMDAxNzY4MDMwNTUyNzAx.af6wqZgaipTQHmw8RIN06I-gIhXGuVtGzbduCmr8X1wg.XVTV8lobBvWKo3HVOKrgHMexTHsFVvpIp7IkHZ2m9Log.PNG%2F%EC%A0%9C%EB%AA%A9%EC%9D%84_%EC%9E%85%EB%A0%A5%ED%95%B4%EC%A3%BC%EC%84%B8%EC%9A%94._-_2026-01-10T163536.801.png%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/pshhh9301","name":"쇠버랜드","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA1MTBfMjE1%2FMDAxNzE1MzUzMDczNzI0.kVY8_MB2gUMJqtEVB7g4zI9sFl16B5QCSFmrQKzFJbsg.BYuKYGsdmNL9pJ5OE-sPGXGoxsr0l_q4nRakhLJuHyAg.JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc6"},{"@type":"MATERIAL-PC-FEED","title":"그냥 피로인줄..혈액암 의심 증상 TOP6, 언제 병원가는게 좋을까?","url":"https://blog.naver.com/yumtt-/224141350688","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMDZfMjQ2%2FMDAxNzY3NjY2OTIwNjU0.v9vlQ0P4ilYnWyP-JdKGrCMhOQAQnY4qH-vIzxLM1J4g.kIzt4zsSsinJTB55AN4i3CqahcZLzBfQiM2FDLzsOPMg.JPEG%2FFrame_5767.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/yumtt-","name":"건강습관사전 윰티","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTAyMjRfMTQ2%2FMDAxNzQwMzc0ODI4NTYz.-DFtnFR5cjyCUkA-zZpZ9EMUhu_1dp1ERmdL5lIncgsg.Iprll-ffVfrI9cbwtJIInXGvhBsEEQsBOP-VrCQyptIg.JPEG%2FFrame_5679.jpg%2FFrame%252B5679.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc7"},{"@type":"MATERIAL-PC-FEED","title":"뛰기보다 100배 효과 운동","url":"https://tv.naver.com/h/91692143","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260106_216%2Fg9yB4_1767704356700pi2GA_JPEG%2FRnnTPNhSgK_02.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/daviddiet","name":"다이어트천재_캡틴D","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240822_136%2FQlTg4_1724297131721OCTc8_JPEG%2F1724297131605.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:23"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc8"},{"@type":"MATERIAL-PC-FEED","title":"체중은 그대로인데 라인이 무너질때 , 몸에서 벌어지는 일 !! 건강한 다이어트","url":"https://blog.naver.com/dmswude/224141165515","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMTBfNjkg%2FMDAxNzY3OTc4ODM3OTc5.H-yNt4MlM85QVeywnwti60vPjDjp5aiDgX0xEfwk6Lgg.BZ4hXzo6fnacJshyjb_KQcKSys2Y_amTKOoKcIyVTRwg.PNG%2F%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2026-01-10_%EC%98%A4%EC%A0%84_2.13.34.png%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/dmswude","name":"김사과","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA3MDZfMTEw%2FMDAxNzIwMjc2NzgzMjMz.J5GcF4246qi8kiu_2_Ifx6dNH3Xdb2SZdllnxP7s5Tgg.GqGeGtxgD3URo98FSVlWpv6toJtBnV-7pb1Op5VaCtEg.PNG%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc9"},{"@type":"MATERIAL-PC-FEED","title":"암 만성염증 치매 유발하는 가장 흔한 음식","url":"https://tv.naver.com/h/91779474","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260108_95%2FIxyOu_1767803438628V4oLS_JPEG%2F65WMFL06wj_01.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://tv.naver.com/ueyaksa","name":"유이 건강","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20251112_251%2Fzce0V_1762928244835VGjxv_PNG%2Fimage.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:52"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cca"},{"@type":"MATERIAL-PC-FEED","title":"아주 죽지 않을 만큼 먹은지 5일차, 한가지 확실한 변화","url":"https://blog.naver.com/chacha_404/224140356888","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAxMDlfMjIw%2FMDAxNzY3OTI3NTg5MDA3.jG0P3aPuJkhb_UQ8AWofM8MMC-qThj-lDdyS4C5jNN0g.RPEO_itwjNFMuPwvSUpYToaTDtI8ks4XTDk7730I6NQg.JPEG%2F139A5255_5.jpg%22&type=nf308_200&service=navermain"},"source":{"url":"https://blog.naver.com/chacha_404","name":"듀꼰이","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTA0MTJfMjQ2%2FMDAxNzQ0NDY0NjE5MDU4.Bh4hAR56slWquXUcWdVQg9hfK4OzrBKSCEPm0yahsscg.JUdCfqqt7SySiHrw08-IaLFVGFwlUM39DZUG0jwkI84g.PNG%2FprofileImage.png%22&type=nf40_40&service=naverm

### 해당 페이지의 title만 출력해보기

In [5]:
import requests

url = 'https://snuco.snu.ac.kr/foodmenu/'
html = requests.get(url).text

title_begin = html.index('<title>')
title_end = html.index('</title>')
title = html[title_begin+len('<title>') : title_end]

print(title)

식단 - 서울대학교 생활협동조합

### 주식의 종목코드로 기업 이름 알아내기

In [6]:
import requests

code = '005930'
url = 'https://finance.naver.com/item/main.nhn?code='
html = requests.get(url + code).text

title_begin = html.index('<title>')
title_end = html.index('</title>')
title = html[title_begin : title_end]

print(title)

<title>삼성전자 : Npay 증권

# OPEN API 사용

- https://www.data.go.kr/data/15098771/openapi.do

In [8]:
!pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.1

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import requests
import os
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

# 환경변수에서 서비스키 불러오기
key = os.getenv("API_KEY")

url = 'http://apis.data.go.kr/1352000/ODMS_COVID_05/callCovid05Api' \
      + '?serviceKey=' + key \
      + '&pageNo=1' \
      + '&numOfRows=10' \
      + '&create_dt=2022-01-08'

xml = requests.get(url).text
print(xml)

<?xml version="1.0" encoding="UTF-8"?>
<response>
 <header>
  <resultCode>00</resultCode>
  <resultMsg>NORMAL SERVICE</resultMsg>
 </header>
 <body>
  <items>
   <item>
    <confCase>53179</confCase>
    <confCaseRate>8.05</confCaseRate>
    <criticalRate>0.01</criticalRate>
    <death>3</death>
    <deathRate>0.05</deathRate>
    <gubun>0-9</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>98569</confCase>
    <confCaseRate>14.91</confCaseRate>
    <criticalRate>0.01</criticalRate>
    <death>13</death>
    <deathRate>0.22</deathRate>
    <gubun>20-29</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>95445</confCase>
    <confCaseRate>14.44</confCaseRate>
    <criticalRate>0.3</criticalRate>
    <death>287</death>
    <deathRate>4.79</deathRate>
    <gubun>50-59</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>39526</confCase>
    <confCaseRate>5.98</confCaseRate>
    <criticalRate>4.16</criticalRate>
    <death>1645</death>
    <deathRate>27.48</deathRate>
    <gubun>70-79</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>93129</confCase>
    <confCaseRate>14.09</confCaseRate>
    <criticalRate>1.01</criticalRate>
    <death>942</death>
    <deathRate>15.74</deathRate>
    <gubun>60-69</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>343420</confCase>
    <confCaseRate>51.95</confCaseRate>
    <criticalRate>0.9</criticalRate>
    <death>3079</death>
    <deathRate>51.44</deathRate>
    <gubun>남성</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>317595</confCase>
    <confCaseRate>48.05</confCaseRate>
    <criticalRate>0.92</criticalRate>
    <death>2907</death>
    <deathRate>48.56</deathRate>
    <gubun>여성</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>96928</confCase>
    <confCaseRate>14.66</confCaseRate>
    <criticalRate>0.08</criticalRate>
    <death>82</death>
    <deathRate>1.37</deathRate>
    <gubun>40-49</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>21156</confCase>
    <confCaseRate>3.2</confCaseRate>
    <criticalRate>14.06</criticalRate>
    <death>2975</death>
    <deathRate>49.70</deathRate>
    <gubun>80 이상</gubun>
    <createDt>2022-01-08</createDt>
   </item>
   <item>
    <confCase>96428</confCase>
    <confCaseRate>14.59</confCaseRate>
    <criticalRate>0.04</criticalRate>
    <death>39</death>
    <deathRate>0.65</deathRate>
    <gubun>30-39</gubun>
    <createDt>2022-01-08</createDt>
   </item>
  </items>
  <numOfRows>10</numOfRows>
  <pageNo>1</pageNo>
  <totalCount>11</totalCount>
 </body>
</response>

In [11]:
from bs4 import BeautifulSoup

xml = requests.get(url).text
bs = BeautifulSoup(xml, "xml") 
items = bs.select('item')

for item in items:
    confCase = item.select_one('confCase').text
    gubun = item.select_one('gubun').text
    print('구분', gubun, '확진자', confCase)

FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime, timedelta
import os
from dotenv import load_dotenv

load_dotenv()
key = os.getenv("API_KEY")

base_url = "http://apis.data.go.kr/1352000/ODMS_COVID_05/callCovid05Api"

# 날짜 범위 설정
start_date = datetime(2022, 1, 1)
end_date = datetime(2022, 1, 10)

date_list = [
    (start_date + timedelta(days=i)).strftime("%Y-%m-%d")
    for i in range((end_date - start_date).days + 1)
]

In [ ]:
data = []

for date in date_list:
    url = (
        f"{base_url}"
        f"?serviceKey={key}"
        f"&pageNo=1"
        f"&numOfRows=10"
        f"&create_dt={date}"
    )

    response = requests.get(url)
    bs = BeautifulSoup(response.text, "xml")
    items = bs.select("item")

    for item in items:
        gubun = item.select_one("gubun").text
        confCase = item.select_one("confCase").text

        data.append({
            "날짜": date,
            "구분": gubun,
            "확진자수": int(confCase)
        })

In [ ]:
df = pd.DataFrame(data)
df.tail()

            날짜     구분    확진자수
95  2022-01-10  50-59   96230
96  2022-01-10  10-19   67513
97  2022-01-10     남성  346703
98  2022-01-10  20-29   99575
99  2022-01-10    0-9   53998

In [ ]:
# 결측/중복 점검
print(df.isna().sum())
print("중복 행 개수:", df.duplicated().sum())

df.head()

날짜      0
구분      0
확진자수    0
dtype: int64
중복 행 개수: 0

           날짜     구분   확진자수
0  2022-01-01  20-29  94950
1  2022-01-01  50-59  92150
2  2022-01-01  30-39  92347
3  2022-01-01  60-69  90422
4  2022-01-01  70-79  38608

In [ ]:
# 연령대 데이터만 남기기 (숫자-숫자 or '이상' 포함)
age_df = df[df['구분'].str.contains(r'\d')].copy()

In [ ]:
def extract_age(group):
    if '이상' in group:
        return int(group.replace(' 이상', ''))
    else:
        return int(group.split('-')[0])

age_df['연령대'] = age_df['구분'].apply(extract_age)

In [ ]:
pivot_df = pd.pivot_table(
    age_df,
    values='확진자수',
    index='날짜',
    columns='연령대',
    aggfunc='sum'
)

pivot_df

연령대,0,10,20,30,40,50,60,70,80
날짜,,,,,,,,,
2022-01-01,49825.0,NaN,94950.0,92347.0,92810.0,92150.0,90422.0,38608.0,20618.0
2022-01-02,50345.0,63989.0,95429.0,92929.0,93405.0,92648.0,90880.0,38763.0,20695.0
2022-01-03,50834.0,64376.0,95818.0,93403.0,93897.0,93010.0,91227.0,38886.0,20756.0
2022-01-04,51249.0,64732.0,96241.0,93877.0,94355.0,93403.0,NaN,38984.0,20821.0
2022-01-05,51771.0,65287.0,96819.0,94631.0,95112.0,93963.0,92004.0,39153.0,20929.0
2022-01-06,NaN,65794.0,97431.0,95262.0,95799.0,94469.0,92411.0,39283.0,21018.0
2022-01-07,52769.0,66248.0,98000.0,95875.0,96403.0,NaN,92763.0,39394.0,21105.0
2022-01-08,53179.0,NaN,98569.0,96428.0,96928.0,95445.0,93129.0,39526.0,21156.0
2022-01-09,53602.0,67110.0,99098.0,96958.0,NaN,95860.0,93452.0,39636.0,21222.0
2022-01-10,53998.0,67513.0,99575.0,97412.0,97924.0,96230.0,NaN,39730.0,21295.0

## naver api 뉴스 검색

- https://developers.naver.com/apps/#/register
- 해당 사이트에서 api 키를 발급받습니다.

In [12]:
import requests
import os
from dotenv import load_dotenv

load_dotenv()

# 환경변수 불러오기
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")

url = "https://openapi.naver.com/v1/search/news.json"

headers = {
    "X-Naver-Client-Id": CLIENT_ID,
    "X-Naver-Client-Secret": CLIENT_SECRET
}

params = {
    "query": "인공지능",
    "display": 5,
    "start": 1,
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

# 결과 확인
print(data)

{'lastBuildDate': 'Mon, 12 Jan 2026 15:30:11 +0900', 'total': 3585178, 'start': 1, 'display': 5, 'items': [{'title': '부산 기장군, 군민 정보화교육에 <b>인공지능</b>(AI) 교육과정 도입', 'originallink': 'http://www.lawissue.co.kr/view.php?ud=2026011215235459719a8c8bf58f_12', 'link': 'http://www.lawissue.co.kr/view.php?ud=2026011215235459719a8c8bf58f_12', 'description': '부산 기장군(군수 정종복)은 1월 19일부터 급속히 확산되는 <b>인공지능</b>(AI) 기술변화에 선제적으로 대응하고 군민의 디지털 활용 역량을 높이기 위해, 군민 정보화교육에 <b>인공지능</b>(AI) 과정을 도입하는 특수시책을... ', 'pubDate': 'Mon, 12 Jan 2026 15:28:00 +0900'}, {'title': "서울시, '창의행정'으로 글로벌 톱5·강북 전성시대 '본격' 시동", 'originallink': 'https://www.asiatoday.co.kr/view.php?key=20260112010005293', 'link': 'https://www.asiatoday.co.kr/view.php?key=20260112010005293', 'description': '특히 6·3 지방선거를 4개월여 앞둔 시점에서 행정 전반에 <b>인공지능</b>(AI) 활용을 확대하고, 강북 대개조를 중심으로 도시 구조를 바꿔 시민이 체감하는 변화를 끌어올려 글로벌 톱5 도시로 업그레이드하겠다는 구상이다.... ', 'pubDate': 'Mon, 12 Jan 2026 15:28:00 +0900'}, {'title': '기상청, 제43회 기상기후 사진·콘텐츠 공모전 개최', 'originallink': 'https://www.public25.com/news/articleView.html?idxno=36989', 'link': 'https://www.public25.com/news/articleView.html?idxno=36989', 'description': '공모 부문은 사진, 영상, 생성형 <b>인공지능</b>(AI) 등 3가지 분야로 나뉜다. 특히 올해 신설된 생성형 <b>인공지능</b>(AI) 부문은 최근의 이례적인 날씨와 기후변화를 국민의 시각에서 참신하게 표현할 수 있도록 마련된 시각... ', 'pubDate': 'Mon, 12 Jan 2026 15:28:00 +0900'}, {'title': 'AI 전문인력 양성 위한 ‘AI 캠퍼스’ 신설…훈련수당도 지급', 'originallink': 'https://www.donga.com/news/Society/article/all/20260112/133137879/1', 'link': 'https://n.news.naver.com/mnews/article/020/0003688648?sid=102', 'description': '정부가 <b>인공지능</b>(AI) 전문인력 1만 명 양성을 지원한다. 고용노동부와 한국기술교육대는 올해부터 AI 전문인력 양성을 위한 K-디지털 트레이닝(KDT) ‘AI 캠퍼스’를 운영한다고 12일 밝혔다. K-디지털 트레이닝은 정부... ', 'pubDate': 'Mon, 12 Jan 2026 15:28:00 +0900'}, {'title': "카카오 준법과신뢰위원회, '연간보고서 2025' 발간", 'originallink': 'https://www.g-enews.com/view.php?ud=2026011214490993383d7a510102_1', 'link': 'https://www.g-enews.com/view.php?ud=2026011214490993383d7a510102_1', 'description': '정 의장은 준신위가 형성한 준법 신뢰 중심 문화를 기반으로 <b>인공지능</b>(AI) 생태계 확장과 글로벌 성장을 도모해 지속적인 성장을 추진하겠다며 같은 목표를 향해 나아가는 논의 파트너가 되길 희망했다. 준 신위는 의장... ', 'pubDate': 'Mon, 12 Jan 2026 15:28:00 +0900'}]}

In [13]:
items = data.get("items", [])
print("items count:", len(items))

# 첫 데이터만 구조 확인
if items:
    print(items[0].keys())

items count: 5
dict_keys(['title', 'originallink', 'link', 'description', 'pubDate'])

In [14]:
import pandas as pd
import re
from html import unescape

def clean_html(text: str) -> str:
    if text is None:
        return ""
    text = unescape(text)
    # <b>...</b> 같은 태그 제거
    return re.sub(r"<.*?>", "", text)

rows = []
for it in items:
    rows.append({
        "title": clean_html(it.get("title")),
        "description": clean_html(it.get("description")),
        "link": it.get("link"),
        "pubDate": it.get("pubDate"),
        "originallink": it.get("originallink"),
    })

df = pd.DataFrame(rows)
df

,title,description,link,pubDate,originallink
0,"부산 기장군, 군민 정보화교육에 인공지능(AI) 교육과정 도입",부산 기장군(군수 정종복)은 1월 19일부터 급속히 확산되는 인공지능(AI) 기술변...,http://www.lawissue.co.kr/view.php?ud=20260112...,"Mon, 12 Jan 2026 15:28:00 +0900",http://www.lawissue.co.kr/view.php?ud=20260112...
1,"서울시, '창의행정'으로 글로벌 톱5·강북 전성시대 '본격' 시동",특히 6·3 지방선거를 4개월여 앞둔 시점에서 행정 전반에 인공지능(AI) 활용을 ...,https://www.asiatoday.co.kr/view.php?key=20260...,"Mon, 12 Jan 2026 15:28:00 +0900",https://www.asiatoday.co.kr/view.php?key=20260...
2,"기상청, 제43회 기상기후 사진·콘텐츠 공모전 개최","공모 부문은 사진, 영상, 생성형 인공지능(AI) 등 3가지 분야로 나뉜다. 특히 ...",https://www.public25.com/news/articleView.html...,"Mon, 12 Jan 2026 15:28:00 +0900",https://www.public25.com/news/articleView.html...
3,AI 전문인력 양성 위한 ‘AI 캠퍼스’ 신설…훈련수당도 지급,정부가 인공지능(AI) 전문인력 1만 명 양성을 지원한다. 고용노동부와 한국기술교육...,https://n.news.naver.com/mnews/article/020/000...,"Mon, 12 Jan 2026 15:28:00 +0900",https://www.donga.com/news/Society/article/all...
4,"카카오 준법과신뢰위원회, '연간보고서 2025' 발간",정 의장은 준신위가 형성한 준법 신뢰 중심 문화를 기반으로 인공지능(AI) 생태계 ...,https://www.g-enews.com/view.php?ud=2026011214...,"Mon, 12 Jan 2026 15:28:00 +0900",https://www.g-enews.com/view.php?ud=2026011214...

In [15]:
df["pubDate"] = pd.to_datetime(df["pubDate"], errors="coerce")
df = df.sort_values("pubDate", ascending=False).reset_index(drop=True)

df[["pubDate", "title"]].head()

                    pubDate                                 title
0 2026-01-12 15:28:00+09:00    부산 기장군, 군민 정보화교육에 인공지능(AI) 교육과정 도입
1 2026-01-12 15:28:00+09:00  서울시, '창의행정'으로 글로벌 톱5·강북 전성시대 '본격' 시동
2 2026-01-12 15:28:00+09:00          기상청, 제43회 기상기후 사진·콘텐츠 공모전 개최
3 2026-01-12 15:28:00+09:00    AI 전문인력 양성 위한 ‘AI 캠퍼스’ 신설…훈련수당도 지급
4 2026-01-12 15:28:00+09:00         카카오 준법과신뢰위원회, '연간보고서 2025' 발간

In [16]:
output_path = "naver_news_ai.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")
print("saved:", output_path)

saved: naver_news_ai.csv